targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          exclude:
            - "test/integration/**/vm_test.dart*"
          include:
            - "example/**.dart"
            - "test/integration/**.browser_test.dart"
            - "test/unit/**.browser_test.dart"